### ISSUE TITLE
Increase padding between session buttons and pages indicator

### ISSUE THREAD

**Issue by UriHerrera** [nx-desktop/nx-simplemenu-applet#1]
![](http://i.imgur.com/TmcL8Tj.png)

These items are too close to each other and the itemview is cutoff when the mouse is over one of the buttons also the indicators of the pages are too close to the bottom. 

![](http://i.imgur.com/Rd3amNs.png)

Like this the itemview has enough space to be displayed entirely. The space below the indicators of the pages is for symmetry.

**Comment by azubieta** [comment]
Done, please check it.

**Comment by UriHerrera** [comment]
Great
