### ISSUE TITLE
Usability of dots for paging 

### ISSUE THREAD

**Issue by UriHerrera** [nx-desktop/nx-simplemenu-applet#11]
> Taken from: https://twitter.com/YurySoloviov/status/983286739811921920
> Basically UX of paging with tiny clickable elements is not the best thing ever.
> 
>

**Comment by star-buck** [comment]
It works with mousewheel scrolling and grabndrag?

**Comment by UriHerrera** [comment]
> It works with mousewheel scrolling and grabndrag?

Yep, scrolling with the mouse wheel and click and drag (swipe) gestures work.
