### ISSUE TITLE
Start menu enhancement.

### ISSUE THREAD

**Issue by geekyBoogiepop** [nx-desktop/nx-simplemenu-applet#18]
When I open the menu and then it should close pressing the _Super_ key, also if I want to look for some program by typing after open the menu doesn't work.
In addition to the first issue with the menu, when I'm using a program (e.g. VSCode) and I open the menu by pressing super key, it gets the focus, but when I close it by pressing _Esc_ key, the focus doesn't revert to previous program.

**Comment by UriHerrera** [comment]
Closing as a dupe of https://github.com/nomad-desktop/nomad-simplemenu-applet/issues/8
