### ISSUE TITLE
Folders in Menu

### ISSUE THREAD

**Issue by UriHerrera** [nx-desktop/nx-simplemenu-applet#2]
I was thinking that it'd a nice feature that the menu was able to create folders (like Gnome Shell does) to organize the apps.

**Comment by azubieta** [comment]
I which version of Gnome Shell is present this feature? Just to take a look at it.

**Comment by UriHerrera** [comment]
Any recent version. you could try Ubuntu Gnome 17.04

**Comment by azubieta** [comment]
It requires more than a cosmetic change, I working on a remake of the backend in order to support apps grouping.

**Comment by azubieta** [comment]
@UriHerrera  This is how it looks by the moment, any comments about the design are more than wellcome. Also if you came up with an idea of how to make the configuration view please share it.  

![screenshot_20170509_114228](https://cloud.githubusercontent.com/assets/1138094/25861113/bf5422aa-34b1-11e7-97b6-b7ddfd74cd6a.png)

**Comment by UriHerrera** [comment]
@azubieta Folder view looks great. Perhaps add a bit of padding to the edges of the area that covers the selection of apps inside the folder.

Is there a limitation on how many apps can be added to a folder?, if not, use a scrollbar (vertical) to list larger groups.

**Comment by star-buck** [comment]
Yes, it looks great!

**Comment by azubieta** [comment]
These are settings view
![screenshot_20170510_142143](https://cloud.githubusercontent.com/assets/1138094/25915983/2d001bd0-3591-11e7-8231-167a0796ba9d.png)
![screenshot_20170510_142207](https://cloud.githubusercontent.com/assets/1138094/25915984/2d053ca0-3591-11e7-923f-ac2bfae13d25.png)

**Comment by UriHerrera** [comment]
@azubieta Ah that is nice, yeah. What icon did you use in "Groups" so I can add it?.

**Comment by azubieta** [comment]
@UriHerrera  the icon that is in the config entry is "object-group" de Breeze
