### ISSUE TITLE
CMake Error

### ISSUE THREAD

**Issue by Samson7** [nx-desktop/nx-simplemenu-applet#22]
[CMakeOutput.log](https://github.com/nx-desktop/nx-simplemenu-applet/files/3671554/CMakeOutput.log)
When I try to build nx-simplemenu-applet with following command i catch an error:
$ cmake -DCMAKE_INSTALL_PREFIX=`kde4-config --prefix` -DCMAKE_BUILD_TYPE=Release -DLIB_INSTALL_DIR=lib -DKDE_INSTALL_USE_QT_SYS_PATHS=ON ../
bash: kde4-config: команда не найдена
CMake Error at /usr/local/share/ECM/cmake/ECMConfig.cmake:11 (message):
  File or directory /usr/local/include/KF5 referenced by variable
  PlasmaQuick_INCLUDE_DIR does not exist !
Call Stack (most recent call first):
  /usr/lib64/cmake/KF5PlasmaQuick/KF5PlasmaQuickConfig.cmake:45 (set_and_check)
  /usr/local/share/ECM/find-modules/FindKF5.cmake:74 (find_package)
  CMakeLists.txt:30 (find_package)

-- Configuring incomplete, errors occurred!
See also "/home/asgard/Загрузки/nx-simplemenu-applet/build/CMakeFiles/CMakeOutput.log".

**Comment by azubieta** [comment]
Hi!
Would you mind to set the output language to English so we can have a better understanding of the error. You can use `export LC_ALL=us` before running `cmake`.

**Comment by Samson7** [comment]
> Hi!
> Would you mind to set the output language to English so we can have a better understanding of the error. You can use `export LC_ALL=us` before running `cmake`.

I solved the problem by copying the folder /usr/include/KF5 to /usr/local/include/KF5 but I did not find this applet in the widget list, how i can add them to panel?

**Comment by azubieta** [comment]
It seems to be that  your KF5 installation path is not being reported properly. Please make sure that  `kde4-config` is installed in your system before configuring the project build.

**Comment by azubieta** [comment]
Or better use this `qtpaths` instead of `kde4-config` as follows:
```
cmake -DCMAKE_INSTALL_PREFIX=`qtpaths --install-prefix` -DCMAKE_BUILD_TYPE=Release -DLIB_INSTALL_DIR=lib -DKDE_INSTALL_USE_QT_SYS_PATHS=ON ../

````
